# Setup warewulf head VM
---
- name: Setup HPC head node
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/vars_vault.yaml
    - vars/package_urls.yaml
    - vars/node_config.yaml
  tasks:
  # - name: Debug print variables
  #   ansible.builtin.include_role:
  #     name: setup-ww
  #     tasks_from: debug_var
  - name: Install HPC head node
    ansible.builtin.include_role:
      name: setup-hpc
      tasks_from: install_hpc_head
  - name: Setup Warewulf on HPC head node
    ansible.builtin.include_role:
      name: setup-hpc
      tasks_from: configure_ww_head
